# Define /wallpapers/ folder path
$wallpaperFolderPath = /home/justice/images/wallpapers

# Define paths to individual wallpapers
$nausicaa = $wallpaperFolderPath/nausicaa_cover.jpg

preload = $nausicaa
splash = false

wallpaper {
  monitor =
  path = $nausicaa
}
