# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# Launch services
exec-once = $uwsmPrefix swaync
exec-once = $uwsmPrefix waybar
exec-once = $uwsmPrefix hyprpaper

# Stuff for cliphist
exec-once = $uwsmPrefix wl-paste --type text --watch cliphist store
exec-once = $uwsmPrefix wl-paste --type image --watch cliphist store

# Startup initial apps
exec-once = [workspace special:specialbtop silent] $uwsmPrefix $terminal --app-id=specialbtop -e btop

exec-once = [workspace 1] $uwsmPrefix discord
exec-once = [workspace 1] $uwsmPrefix spotify-launcher

exec-once = [workspace 2] $uwsmPrefix firefox
