# See https://wiki.hyprland.org/Configuring/Keywords/

# Set up UWSM application startup prefix
$uwsmPrefix = uwsm app --

# Sets "Windows" key as main modifier
$mainMod = SUPER

# Set programs that you use
$editor = nvim
$terminal = foot 2>/dev/null
$fileManager = $terminal ~/.local/bin/yaziccwd.sh
$menu = fuzzel --launch-prefix="uwsm app -- "
