# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on

# Rules for special btop workspace
windowrule = match:class specialbtop, float on, size (monitor_w*0.92) (monitor_h*0.92), move (monitor_w*0.04) (monitor_h*0.04), animation popin

# Force apps to start in specific workspaces initially with no focus
windowrule = match:class discord, workspace 1, no_initial_focus on
windowrule = match:class spotify, workspace 1, no_initial_focus on

# Firefox should not have transparency
windowrule = match:class firefox, opacity 1.0 override

# Remove border and gaps when window is alone in workspace
workspace = w[t1], gapsout:0, gapsin:0
workspace = w[tg1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = match:workspace w[t1], match:float 0, border_size 0, rounding 0
windowrule = match:workspace w[tg1], match:float 0, border_size 0, rounding 0
windowrule = match:workspace f[1], match:float 0, border_size 0, rounding 0
